### PR TITLE
✨Resume process

### LINKED ISSUE #167: ✨ "Resume process" functionality
#### Describe your issue

We need a way to restart processes that were unfinished when the process engine last terminated. 

To achieve this, we should add a function for retrieving all process instances that were still running, the last time the `ProcessEngine` was stopped and resume said instances from the `FlowNodeInstance` at which they stopped.

This function must be run before all others.

#### Possible Solution

To implement this, we need to do the following:
- Add a `previousFlowNodeInstanceId` field to the `FlowNodeInstance` object, because we need to be able to reconstruct a process' execution path and `ProcessToken` history
- Implement a `ResumeProcessService` that holds all functionality for resuming processes. It can use the existing Handlers to do its job, but I do not want this to be part of the `ExecuteProcessService`, as that would only make this service extremely bloated and harder to understand, because it would have to know the difference between new `ProcessInstances` and resumed `ProcessInstances`.
- We'll need some kind of logic that allows us to bypass the `onEnter` and `onSuspend` persistence, since the interrupted FlowNodeInstances will already have been persisted at that time.
  - Off hand, I'd like to do this in the `FlowNodeInstanceRepository`. Implementing a check for an existing Token there is far easier an cleaner than refactoring all existing FlowNodeHandlers.

The `ResumeProcessService` needs to do the following:
1. Retrieve all running FlowNodeInstances from the database
2. Create some kind of "profile" for each `ProcessInstance` that was prematurely interrupted. These profiles will, in essence, group all active `FlowNodeInstances` by their respective `ProcessInstance` and contain its full `FlowNodeInstance` history.
 - For Example: Lets say, we have three active `FlowNodeInstances` FNI1, FNI2 and FNI3.
 - FNI1 and FNI1 belong to ProcessInstance1, FNI3 belongs to ProcessInstance2.
 - The `ResumeProcessService` will create two profiles for these Instances: One for ProcessInstance1 and one for ProcessInstance2. These contain all the active `FlowNodeInstances`, aswell as a full history of all previously executed `FlowNodeInstances`.
 - It should suffice to get only the `ProcessToken` of each previously finished `FlowNodeInstance`, since that is always the info that is passed to each `FlowNodeHandler`.
3. Create a `ProcessModelFacade` and `ProcessTokenFacade` for each `ProcessInstance` to be resumed and fill them with info about the already finished `FlowNodeInstances`.
4. Start each `ProcessInstance` from the `FlowNode` that was last being executed. We can use the existing `FlowNodeHandlers` for this. Most of the handling should be pretty straight forward, however there are a few special cases:
4.1. When resuming Timer-Events we need to watch out for existing persisted timers. These should be wiped beforehand, because we won't be able to tell just how for these had progressed before the process was interrupted anyway. Also, since there is an obvious time gap, any existing timer would be worthless, because we will most likely have passed the timers scheduled duration already.
4.2. When dealing with `ParallelGateways`, we have to restart each parallel running branch and let them run in concert. This could be tricky, as we need to resume those branches at the moment they were interrupted, not from the beginning. This will probably require a new kind of ParallelGatewayHandler designed for this sort of thing.
4.3. We must ensure that Calls in a ServiceTask which were already executed, but not persisted, will not be executed again. When the ProcessEngine crashes, there is not much we can do about this, but we *can* implement a kind of "safe shutdown", that will prevent the ProcessEngine from exiting, until the ServiceTask has been completed.
5. The resumed ProcessInstances should now be continuing from the point at which they were previously interrupted.
6. **IMPORTANT**: Calling the `resumeProcess` function must **NOT** be awaited! Otherwise, whoever calls this function won't be able to do anything else until all the resumed processes have finished!

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

### PR DESCRIPTION
**Pull request by ElRaptorus**
**Requires:**
https://github.com/process-engine/process_engine_contracts/pull/85

**Changes:**

1. Implement the `ResumeProcessService` for resuming previously interrupted Processes on startup.
2. Implement the `resume` function for each FlowNodeHandler.
3. Add logging to the more complex handlers.

The workflow for resuming ProcessInstances works like this:
- The `ResumeProcessService` retrieves all active FlowNodeInstances from the database
    - This includes only FlowNodeInstances that are marked as `suspended` or `running`
- The service then retrieves the list of active ProcessInstances from the retrieved list of FlowNodeInstances
    - This is done to avoid resuming the same ProcessInstance twice, which could happen, if a ProcessInstance with multiple parallel branches was interrupted
    - Also, this step filters out `CallActivities` and `SubProcesses`, since these must be resumed by their respective FlowNodeHandlers.
- Each retrieved ProcessInstance is "resumed" from the StartEvent by which it was originally started.
- The entire FlowNode chain is being traversed, using each FlowNodeHandlers `resume` function as the main entry point
    - To be able to correctly resume, each handlers `resume` function will get a matching FlowNodeInstance injected into it. This instance contains all information necessary for the handler to do its work.
- Depending on where the indiviudal FlowNode was interrupted, the FlowNodeHandler will continue to execute the FlowNode, until it is finished. The base class provides four separate hooks for this:
    - `continueAfterEnter`: The FlowNodeInstance was started but didn't get a chance to do its work. The handler is run from the start.
    - `continueAfterSuspend`: The FlowNodeInstance was interrupted while it was suspended. The handler will reconstruct the conditions necessary for placing it in suspension again and then wait for the key event that is supposed to resume the handler.
    - `continueAfterResume`: The FlowNodeInstance was already resumed by the key event that the handler is supposed to wait for. The handler will continue post-execution steps and then finish up.
    - `continueAfterExit`: The FlowNodeInstance was already finished. The handler just adds the instance's final result to the ProcessToken and then exits. This is actually the mechanism that allows us to effortlessly recreate ProcessTokens and resume parallel branches.
- When a `CallActivity` is to be resumed, the handler will:
    - either use the `ResumeProcessService` to resume the respective CallActivity
    - or, if the CallActivity was already finished during the downtime, retrieve the CallActivity result and use it as a result for the FlowNodeInstance.
- The handlers for `ExternalServiceTasks` will do much the same:
    - Check if an ExternalTask was already created. If not, it will be created and the handler waits for it to be processed, just as it normally would
    - If the ExternalTask was already created, the handler will check the state of that ExternalTask. 
         - If it was already finished, its result is retrieved and used as a result for the FlowNodeInstance.
         - If it was not yet finished, the handler will be placed in suspension again and wait for it to be finished
         - This is easily achieved, thanks to the separate persisting of ExternalTasks in a separate repository.
- `ParallelGateways` also work much the same, except that they only perform these steps for the FlowNodes that belong to their branches.
- Resuming a `SubProcess` must be done by the handler itself, not by the `ResumeProcessService`.
    - This is because Subprocesses do not contain xml code of their own and must therefore not create an entry in the `Correlation` repository, which would require the hash of a process model's xml. Doing so would inadvertently cause side effects with the correlation-related functions.
- When all resumable FlowNodeInstances have been successfully resumed and finished, the rest of the Process will continue normally. This means, the succeeding FlowNodeHandlers will no longer be run through their `resume` function, but `execute`.
    - Trying to `resume` them wouldn't make much sense anyway, because there is no instance specific data to pass to them. They were not run yet, after all.
- The ProcessInstance will then just continue to run as it normally would.

**Issues:**

Closes #167 

PR: #208

## How can others test the changes?

Try crashing a few ProcessInstances and then resume them on the next startup.

## PR-Checklist

Please check the boxes in this list after submitting your PR:

- [x] You can merge this PR **right now** (if not, please prefix the title with "WIP: ")
- [x] I've tested **all** changes included in this PR.
- [x] I've also reviewed this PR myself before submitting (e.g. for scrambled letters, typos, etc.).
- [x] I've rebased the `develop` branch with my branch before finishing this PR.
- [x] I've **summarized all changes** in a list above.
- [x] I've mentioned all **PRs, which relate to this one**.
- [x] I've prefixed my Pull Request title is according to [gitmoji guide](https://gitmoji.carloscuesta.me/).

## Example

<details>
<summary>
:warning: Before merging please click here to expand and follow the guide.
</summary>
<br>

Please use `:twisted_rightwards_arrows:` at the beginning of your merge commit title.

Example 1:

<pre>
<code>
:twisted_rightwards_arrows: :bug: Fix Wrong Text Decoration at ...
</code>
</pre>

To get your commit message, just copy the first part of this pull request.

Example 2:
<pre>
<code>
**Changes:**

- Fixes Wrong Text Decoration at ...
- Fixes some typos
- ...

**Issues:**

Closes #NumberOfFixedIssue

PR: #NumberOfThisPR
</code>
</pre>
</details>

## Emojis

<details>
<summary>
Expand for a list of most used Emojis.
</summary>
<br>

Please prefix your commit messages with an Emoji.

Ref: https://gitmoji.carloscuesta.me/

| Description              | Glyphe               | Emoji  |
|--------------------------|----------------------|--------|
| Bugfix                   | `:bug:`              | 🐛     |
| Fixing Security Issues   | `:lock:`             | 🔒     |
| Configuration releated   | `:wrench:`           | 🔧     |
| Cosmetic                 | `:lipstick:`         | 💄     |
| Dependencies Downgrade   | `:arrow_down:`       | ⬇️     |
| Dependencies Upgrade     | `:arrow_up:`         | ⬆️     |
| Formatting               | `:art:`              | 🎨     |
| Improving Performance    | `:zap:`              | ⚡️      |
| Initial commit           | `:tada:`             | 🎉     |
| Linter                   | `:rotating_light:`   | 🚨     |
| Miscellaneous            | `:package:`          | 📦     |
| New Feature              | `:sparkles:`         | ✨     |
| Refactoring Code         | `:recycle:`          | ♻️      |
| Releasing / Version tags | `:bookmark:`         | 🔖     |
| Removing Stuff           | `:fire:`             | 🔥     |
| Tests                    | `:white_check_mark:` | ✅     |
| Work In Progress (WIP)   | `:construction:`     | 🚧     |

</details>

### CODE REVIEW

**Comment by ElRaptorus** [comment]
https://github.com/process-engine/process_engine_runtime/issues/65

File: src/runtime/engine/flow_node_handler/flow_node_handler.ts [hunk 1]
```diff
@@ -121,6 +139,145 @@ export abstract class FlowNodeHandler<TFlowNode extends Model.Base.FlowNode> imp
...
+   * @param   flowNodeInstance   The current ProcessToken.
+   * @param   processTokenFacade The ProcessTokenFacade of the curently
+   *                             running process.
+   * @param   processModelFacade The ProcessModelFacade of the curently
+   *                             running process.
+   * @param   identity           The identity of the user that originally
+   *                             started the ProcessInstance.
+   * @returns                    The Info for the next FlowNode to run.
+   */
+  protected async abstract resumeInternally(flowNodeInstance: Runtime.Types.FlowNodeInstance,
```
Comment (roblen45) [inline src/runtime/engine/flow_node_handler/flow_node_handler.ts]: Ich glaube diese Methode ist überflüssig.
Die Handler implementieren diese Methode nahezu gleich.
Es gibt immer ein switch wo je nach flownodeinstance.state die jeweiligen Methoden aufgerufen werden.
Diese Unterscheidung sollte in der Basisklasse geschehen und die Handler implementieren nur die Methoden:

1. continueAfterEnter
2. continueAfterSuspend
3. continueAfterResume
4. continueAfterExit
1 und 4 sollten abstract sein, da alle Handler diese implementieren müssen.

File: src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts [hunk 2]
```diff
@@ -38,20 +44,105 @@ export class IntermediateMessageCatchEventHandler extends FlowNodeHandler<Model.
...
+
+  protected async resumeInternally(flowNodeInstance: Runtime.Types.FlowNodeInstance,
+                                   processTokenFacade: IProcessTokenFacade,
+                                   processModelFacade: IProcessModelFacade,
+                                   identity: IIdentity,
+                                 ): Promise<NextFlowNodeInfo> {
+
+    this.logger.verbose(`Resuming MessageCatchEvent instance ${flowNodeInstance.id}`);
+
+    function getFlowNodeInstanceTokenByType(tokenType: Runtime.Types.ProcessTokenType): Runtime.Types.ProcessToken {
```
Comment (roblen45) [inline src/runtime/engine/flow_node_handler/intermediate_event_handlers/intermediate_message_catch_event_handler.ts]: Diese Methode wird in allen Handler benötigt und operiert nur auf den Daten der FlowNodeInstance
=> Methode in FlowNodeInstance implementieren.

File: src/runtime/engine/flow_node_handler/flow_node_handler.ts [hunk 3]
```diff
@@ -121,6 +139,145 @@ export abstract class FlowNodeHandler<TFlowNode extends Model.Base.FlowNode> imp
...
+   * Contains all common logic for executing and resuming FlowNodeHandlers.
+   *
+   * @async
+   * @param   token              The FlowNodeInstances current ProcessToken.
+   * @param   processTokenFacade The ProcessTokenFacade to use.
+   * @param   processModelFacade The processModelFacade to use.
+   * @param   identity           The requesting users identity.
+   * @returns                    Info about the next FlowNode to run.
+   */
+  protected async _executeHandler(token: Runtime.Types.ProcessToken,
```
Comment (roblen45) [inline src/runtime/engine/flow_node_handler/flow_node_handler.ts]: Diese Methode ist in der Basisklasse unnötig, da immer Handler spezifisch.

Comment (ElRaptorus) [reply src/runtime/engine/flow_node_handler/flow_node_handler.ts]: Die muss aber in der Basisklasse verfügbar sein, damit die `_continue` hooks auf die zugreifen können.

File: src/runtime/engine/flow_node_handler/flow_node_handler.ts (hunk 1 above)
Comment (ElRaptorus) [reply src/runtime/engine/flow_node_handler/flow_node_handler.ts]: Jo, hab ich auch schon überlegt, allerdings implementieren nicht alle handler die auf die exakt gleiche Art. 
Ebenfalls gibts natürlich noch das Logging.

File: src/runtime/engine/resume_process_serivce.ts [hunk 4]
```diff
@@ -0,0 +1,466 @@
...
+                                currentProcessToken: Runtime.Types.ProcessToken,
+                                processTokenFacade: IProcessTokenFacade,
+                                processModelFacade: IProcessModelFacade,
+                                identity: IIdentity,
+                                flowNodeInstancesForProcessInstance: Array<Runtime.Types.FlowNodeInstance>,
+                               ): Promise<void> {
+
+    const flowNodeHandler: IFlowNodeHandler<Model.Base.FlowNode> = await this._flowNodeHandlerFactory.create(flowNodeToResume, processModelFacade);
+
+    const nextFlowNodeInfo: NextFlowNodeInfo =
```
[the remark this answers is not in the document]
Comment (ElRaptorus) [reply src/runtime/engine/resume_process_serivce.ts]: Bin für Gegenvorschläge offen. 😉 

Wobei ich hier aber gerade nicht den konkreten Zusammenhang mit den ParallelGateways sehe. Die handlen die FlowNodes in ihren Branches selbst, nicht der ResumeProcessService. Der initialisiert nur das Gateway.

File: src/runtime/engine/flow_node_handler/flow_node_handler.ts (hunk 1 above)
Comment (ElRaptorus) [reply src/runtime/engine/flow_node_handler/flow_node_handler.ts]: @roblen45 Done.
Der Base FlowNodeHandler hat jetzt einen `resumeInternally` hook, der `continueAfterEnter` und `continueAfterExit` benutzt. 
Die FlowNodes die nur diese brauchen benutzen jetzt den.
Alle FlowNodes, die auch `continueAfterSuspend` und `continueAfterResume` zusätzlich benötigen, haben nach wie vor eine eigene Implementierung.
